package es.weso.shexl

/**
 * A Shape Expression Compiler Generated Source Represents the source generated by the compiler in an specific target
 * language.
 *
 * @author Guillermo Facundo Colunga
 */
trait ShExLCompilerGeneratedSource {

  /**
   * Gets the standardized target language in which the source has been generated.
   *
   * @return the standardized target language.
   */
  def getLanguage: ShExLCompilerTargetLanguage

  /**
   * Gets the source as a plain String object.
   *
   * @return the source as a plain String object.
   */
  def getSource: String

  /**
   * Writes the generated source in a given filepath.
   *
   * @param filePath is the place where the source will be written.
   */
  def toFile(filePath: String)
}
